
PlotResolutionTimeByReopens <- structure(
function 
##title<< Plot hours to resolution time by the number of reopens 

  ###############################################################################
  # File:  PlotResolutionTimeByReopens.R
  ##author<<  Steven H. Ranney
  ## Contact: \email{Steven.Ranney@gmail.com}
  # Created: 1/07/14  
  # Last Edited: 01/07/14 by SHR
  ##description<< This function plots the chosen value of resolution time (in 
  ## hours) and produces a plot of those values as a function of \code{reopens}. 
  #
  # TODO: add RData for example
  # TODO: add testing section
  ###############################################################################

  (dF, ##<< The dataFrame for which to plot resolution time by priority level.
  resTime = "first" ##<< A character vector that indicates which resolution time
                    ## to plot.  Other values include \code{"full"}.
  ){
    
  dF$reopens <- as.numeric(dF$reopens)
  
  #Handling 'nan.0' values
  dF$first_resolution_time_in_minutes_within_business_hours[dF$first_resolution_time_in_minutes_within_business_hours == "nan.0"] <- NA
  dF$full_resolution_time_in_minutes_within_business_hours[dF$full_resolution_time_in_minutes_within_business_hours == "nan.0"] <- NA

  value <- NA
  if(resTime == "first") dF$value <- as.numeric(dF$first_resolution_time_in_minutes_within_business_hours)
  if(resTime == "full") dF$value <- as.numeric(dF$first_resolution_time_in_minutes_within_business_hours)
  
  if(length(which(is.na(dF$value))) == nrow(dF)){
    stop(print("Data frame has no data to display"))
    } else {
  
  ##details<< Resolution time in all sample dataFrames is \code{factor}; this function
  ## converts apparently numeric values to \code{as.numeric}
  
  ##details<< This functions converts values that are \code{nan.0} to \code{NA}.
  
  ##details<< This function uses a linear model to evaluate the relationship between
  ## the resolution time and the number of reopens.  If the red line 
  ## (the result of the \code{\link{lm}} in the produced plot trends down, then 
  ## the higher the call volume the more times a ticket gets reopened.  If the red 
  ## line is parallel or very near to parallel, then there is no relationship 
  ## between the number of reopens and call volume.  In some cases, there may be 
  ## outliers that exert a high amount of leverage on the model that could cause 
  ## suprious results.  Before drawing conclusions, be sure that you understand the 
  ## data.
  
  ylabel <- NA
  if(resTime == "first") ylabel <- "First resolution (hours)"
  if(resTime == "full") ylabel <- "Full resolution (hours)"
  
  xlabel <- "Number of Reopens"
  
  ##details<< Plots are generated by the function \code{\link{ggplot}}
  g <- ggplot(dF, aes(x = reopens, y = (value/60)))
 
 #Create a linear model of score as a function of wait time (hours)
  lmMod <- lm(dF$value/60~dF$reopens) 
 
    p1 <- g + geom_point() + labs(ylab(ylabel)) + labs(xlab(xlabel)) +  
              geom_abline(intercept=lmMod$coefficients[1], slope=lmMod$coefficients[2], 
                          colour = "red", size = 1.01)

    } #end else
    
  return(p1)
  
  })  
